name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: git clone --depth=1 "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" .

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel Production
        run: |
          TOKEN=$(echo "${{ secrets.VERCEL_TOKEN }}" | tr -d '\xef\xbb\xbf' | tr -d '\r\n')
          vercel --prod --token="$TOKEN" --yes
        env:
          VERCEL_ORG_ID: team_JWq542kltY1brzPvSLqF5jEA
          VERCEL_PROJECT_ID: prj_gGh0bVjKyTPvJN2q8iSb07BkAXLK
